#!/bin/bash
#
#Skript kasutaja vanuse järgi tema ea määramiseks
echo "Sisestage oma vanus: "		#Küsitakse vanust
read vanus
if test $vanus -gt 0 -a $vanus -lt 11	#If käsk vanuse kontrolliks, kas on alla 11
then
echo "Teie olete laps."
elif test $vanus -ge 11 -a $vanus -lt 18#Elif, kui vanus on suurem võrdne 11
then
echo "Teie olete nooruk."
elif test $vanus -ge 18 -a $vanus -lt 63#Elif, kui vanus on suurem võrdne 18
then
echo "Olete täiskasvanud."
elif test $vanus -ge 63			#Elif, kui vanus on suurem võrdne 63
then
echo "Olete vanur."
else
echo "Sisestasite väärtuse valesti."
fi
#Skripti lõpp
