#!/bin/bash
#
#
echo "Sisestage kellaaeg täistunnina: "
read kell
if test $kell -ge 6 -a $kell -lt 12	#If, kui kell on suurem/võrdne 6 ja vähem kui 12
then
echo -n "Ilusat hommikut Teile."
elif test $kell -ge 12 -a $kell -lt 18	#-;;-
then
echo -n "Tere päevast."
elif test $kell -ge 18 -a $kell -lt 22	#-;;-
then
echo -n "Tere õhtust."
elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6 #-;;-
then
echo -n "Head ööd."
else
echo -n "Sisestage arv uuesti."
fi
#Skripti lõpp
