#!/bin/bash
#
#Skript algarvu kontrollimiseks
echo "Sisestage suvaline arv: "
read arv
if [ $arv -eq 0 -o $arv -eq 1 ]	#If, kui arv on võrdne 0 või võrdne 1
then
echo $arv "ei ole algarv."
else
jagaja=2	#Määratakse muutuja jagaja
jaak=$(( $arv % $jagaja ))
while [ $jaak -ne 0 ]	#While loop, kui jääk pole 0
do
	jagaja=$(( $jagaja + 1 ))
	jaak=$(( $arv % $jagaja ))
done
if [ $arv -eq $jagaja ]
then
echo $arv "on algarv."
else
echo $arv "ei ole algarv."
fi
fi
#Skripti lõpp
