#!/bin/bash
#
#kasutaja arvudega kuju väljastamine
echo "Sisestage ridade arv: "
read rida
echo "Sisestage tärnide arv: "
read arv
for (( i = 1; i <= rida; i++ ))
do
	for (( j = 1; j <= arv; j++ ))
	do
		if [ $i -eq 1 -o $i -eq $rida -o $j -eq $arv -o $j -eq 1 ]
		then
			echo -n "* "
		else
			echo -n "  "
		fi
	done
echo ""
done
#Skripti lõpp
