#!/bin/bash
#
#Skript tagurpidi kolmnurga tegemiseks
echo "Sisestage ridade arv: "
read rida
for (( i = 1; i < rida; i++ ))
do
	for (( j = 1; j <= rida - i; j++ ))
	do
	echo -n "* "
	done
echo ""
done
#Skripti lõpp
